.TH EzBuild 1
.SH NAME
ezbuild \- tool for building and testing small programs with minimal configuration
.SH SYNOPSIS
.B ezbuild -re
.SH DESCRIPTION
.B ezbuild
Running ezbuild will check for config files in the current directory or /etc/ezbuild to run configurable commands on a number of local files.
Details on how to configure ezbuild can be found at https://github.com/stuin/ezbuild
